language: node_js
node_js:
  - "5.2"
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm install
before_script:
  - npm install -g bower
  - bower install
  - npm run build
script: 
  - travis_retry npm test
  - ./deploy/s3_deploy.sh
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
